name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch where you push your code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or a recent LTS version

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Build project
        run: npm run build # This uses your updated vite.config.ts to build for the correct base path

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The folder containing your built site
          publish_branch: gh-pages # This is the default branch GitHub Pages looks for when using Actions
