name: Simple Test Workflow

on: [push] # This means: trigger on any push to any branch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from a simple test workflow!"
